name: ~solution Node.js CI

on: [push, pull_request]

defaults:

  run:

    working-directory: packages/~solution

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: |
        npm install --prefix ../..
        npm run lint

  test:

    name: test (Node.js ${{ matrix.node-version }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['12', '14', '16']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm test

  prepare-legacy-test:

    name: prepare legacy test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: |
        npm install --prefix ../..
        npm run prepare-legacy-test
    - uses: actions/upload-artifact@v2
      with:
        name: node-legacy
        path: packages/~solution/test/node-legacy

  legacy-test:

    name: legacy test (Node.js ${{ matrix.node-version }})

    needs: prepare-legacy-test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['0.10', '0.12', '4', '6', '8', '10']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/download-artifact@v2
      with:
        name: node-legacy
        path: packages/~solution/test/node-legacy
    - run: npm run legacy-test
